name: Install and Test
on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
jobs:
  build-linux:
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    name: Python (${{ matrix.PYTHON_VERSION }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.12"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v4

    - name: Add /etc/hosts entries
      run: |
        cat .github/workflows/etchosts.txt | sudo tee -a /etc/hosts

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    # Get postgresql running and setup the database
    - name: Setup Postgres
      run: |
        set -e
        git clone --depth 1 https://github.com/akrherz/iem-database.git database
        git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
        cd .ci_tooling
        . postgres.sh
        cd ..
        cd database; sh bootstrap.sh
        python schema_manager.py

    # Get apache running, which is needed to build mod_wsgi
    - name: Configure IEM Webfarm Server
      run: |
        set -e
        cd .ci_tooling
        . iemwebfarm.sh

